---
# role: ansible-role-virtualbox-guest
# file: .travis.yml

language: python

python:
  - "2.7"
  - "3.6"

services: docker

env:
  matrix:
    - MOLECULE_DIST: 'jam82/molecule-alpine:latest'
    - MOLECULE_DIST: 'jam82/molecule-amazonlinux:latest'
    - MOLECULE_DIST: 'jam82/molecule-archlinux:latest'
    - MOLECULE_DIST: 'jam82/molecule-centos:7'
    - MOLECULE_DIST: 'jam82/molecule-centos:8'
    - MOLECULE_DIST: 'jam82/molecule-debian:9'
    - MOLECULE_DIST: 'jam82/molecule-debian:10'
    - MOLECULE_DIST: 'jam82/molecule-opensuse:15'
    - MOLECULE_DIST: 'jam82/molecule-opensuse:tumbleweed'
    - MOLECULE_DIST: 'jam82/molecule-oraclelinux:7'
    - MOLECULE_DIST: 'jam82/molecule-oraclelinux:8'
    - MOLECULE_DIST: 'jam82/molecule-ubuntu:18.04'
    - MOLECULE_DIST: 'jam82/molecule-ubuntu:20.04'

install:
  - pip install ansible-lint docker flake8 molecule testinfra yamllint

script:
  - molecule --version
  - ansible --version
  - molecule test
