---
# role: ansible-role-virtualbox-guest
# file: tasks/main.yml

- name: "Import tasks for role ansible-role-virtualbox-guest"
  import_tasks: tasks.yml
  when: virtualbox_guest_role_enabled | bool
    and ansible_virtualization_role == "guest"
    and ansible_virtualization_type == "virtualbox"
